version: "3.4"

services:
  sampledb:
    container_name: sampledb
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbSettings:ConnectionString=mongodb://sampledb:27017"
    depends_on:
      - sampledb
    ports:
      - "5000:80"
    volumes:
      - ${HOME}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https:ro
